version: "3.5"

services:
  node:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 4000:4000
    networks:
      - app-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: voltbras
    ports:
      - 5432:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
